name: super_editor_markdown
description: Markdown (de)serialization for super_editor documents.
version: 0.1.5
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  markdown: ^4.0.0

  super_editor:
    git:
      url: https://github.com/batyrkhanurali/super-editor
      ref: main
  attributed_text: ^0.3.0
  super_text_layout: ^0.1.9

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_test_robots: ^0.0.22
  flutter_test_runners: ^0.0.4
  golden_toolkit: ^0.15.0

flutter:
# no Flutter configuration